#### Property file for the garage control remote project
###  Version 1.0 
##   Created by Tanuj & Tarun Siva
####################################################
garControlFileOld=garage.txt.OLD
garageControlFileCloud=/garage/garage.txt

garControlLocalNew=/home/pi/garage/scripts/garage.txt
garControlLocalOld=/home/pi/garage/scripts/garage.txt.OLD

garageHTMLLocalFile=/home/pi/garage/scripts/static/garagestatus.html
garageHTMLRemotFile=/garage/garagestatus.html

dropBox_Script=/home/pi/garage/python/dropbox_uploader.sh

garageDBFullname=/home/pi/garage/scripts/dbutils/garage.db

garage1Name=Garage-Maxima
garage2Name=Garage-Odyssey

# Control file download frequency from Dropbox
controlFileDownloadFreq=60

SendEmailFlag=NO  # YES/NO

garageActivityCloudReportName=/garage/garageactivities.html
garageActivityReport_Template=/home/pi/garage/scripts/static/activitytemplate.html
garageActivityReport_Generatd=/home/pi/garage/scripts/static/activityreport.html

htmlOpenBGTagOpen=background-color: #FF0000; font-size:xx-large;
htmlOpenBGTagShut=background-color: #008000; font-size:xx-large;


# For LED
gar1LedPin = 18
gar2LedPin = 23

# For Relay
gar1RelayPin = 11
gar2RelayPin = 8

# Garage Door Input Signals
gar1SignalPin = 15
gar2SignalPin = 16

